version: 2

models:
  - name: stg_games
    description: "Games table from source data"
    columns:
      - name: game_id
        description: "Unique identifier for the board game."
        tests:
          - not_null
          - unique
      - name: game_name
        description: "Name of the board game."
        tests:
          - not_null
          - unique
      - name: year_published
        description: "Release year of the game."
      - name: min_players
        description: "Minimum number of players required to play."
      - name: max_players
        description: "Maximum number of players allowed."
      - name: game_duration
        description: "Average playing time in minutes."
      - name: min_playing_time
        description: "Minimum estimated playing time."
      - name: max_playing_time
        description: "Maximum estimated playing time."
      - name: min_age
        description: "Minimum recommended age to play."
      - name: game_description
        description: "Description of the game."
      - name: image_path
        description: "URL of the game's image."
      - name: game_rank
        description: "Rank of the game on BoardGameGeek."

  - name: stg_game_ratings
    description: "Ratings and statistics for the games."
    columns:
      - name: game_id
        description: "Unique identifier for the board game."
        tests:
          - not_null
          - unique
      - name: weight
        description: "Complexity weight of the game."
      - name: num_ratings
        description: "Total number of user ratings."
      - name: avg_rating
        description: "Average user rating."
      - name: bayes_avg_rating
        description: "Bayesian average rating."
      - name: num_comments
        description: "Total number of user comments."
      - name: num_weight_votes
        description: "Number of weight votes given by users."
      - name: num_owners
        description: "Number of owners of the game."

  - name: stg_game_recommendations
    description: "Community and manufacturer recommendations for the games."
    columns:
      - name: game_id
        description: "Unique identifier for the board game."
        tests:
          - not_null
          - unique
      - name: community_min_playtime
        description: "Community-recommended minimum playtime."
      - name: community_max_playtime
        description: "Community-recommended maximum playtime."
      - name: community_age_reco
        description: "Community's recommended age for the game."
      - name: manufacturer_age_reco
        description: "Manufacturer-recommended age for the game."
      - name: manufacturer_reco_playtime
        description: "Manufacturer-recommended playtime."
